// Generated by CoffeeScript 1.9.2
(function() {
  var initCSS;

  initCSS = function() {
    var can_aspect, img_aspect, nito_san, nito_san_back, nito_san_img;
    nito_san = $("#nito-san");
    nito_san_img = $("#nito-san img");
    nito_san_back = $("#nito-san-back");
    nito_san.css("height", $(window).height());
    nito_san_back.css("width", nito_san.width());
    nito_san_back.css("height", nito_san.height());
    nito_san_back.css("top", 0);
    img_aspect = nito_san_img.width() / nito_san_img.height();
    can_aspect = nito_san.width() / nito_san.height();
    if (img_aspect < can_aspect) {
      nito_san_img.css("height", nito_san.height());
      nito_san_img.css("width", "auto");
      nito_san_img.css("margin-left", nito_san.width() / 2 - nito_san_img.width() / 2);
      return nito_san_img.css("margin-top", 0);
    } else {
      nito_san_img.css("width", nito_san.width());
      nito_san_img.css("height", "auto");
      nito_san_img.css("margin-left", 0);
      return nito_san_img.css("margin-top", nito_san.height() / 2 - nito_san_img.height() / 2);
    }
  };

  $(function() {
    initCSS();
    return $(window).resize(function() {
      return initCSS();
    });
  });

}).call(this);
